BEGIN;
ALTER TABLE listening_sessions
    ALTER COLUMN created_at SET DATA TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN updated_at SET DATA TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN deleted_at SET DATA TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE login_sessions
    ALTER COLUMN created_at SET DATA TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN updated_at SET DATA TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN deleted_at SET DATA TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE song_requests
    ALTER COLUMN created_at SET DATA TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN updated_at SET DATA TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN deleted_at SET DATA TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE track_metadata
    ALTER COLUMN created_at SET DATA TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN updated_at SET DATA TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN deleted_at SET DATA TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE users
    ALTER COLUMN created_at SET DATA TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN updated_at SET DATA TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN deleted_at SET DATA TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN spotify_token_expiry SET DATA TYPE TIMESTAMP WITH TIME ZONE;
COMMIT;
