BEGIN;
ALTER TABLE playlist_metadata
    ALTER COLUMN created_at SET DATA TYPE TIMESTAMP,
    ALTER COLUMN updated_at SET DATA TYPE TIMESTAMP,
    ALTER COLUMN deleted_at SET DATA TYPE TIMESTAMP;
COMMIT;
