BEGIN;
ALTER TABLE listening_sessions
    ALTER COLUMN created_at SET DATA TYPE TIMESTAMP,
    ALTER COLUMN updated_at SET DATA TYPE TIMESTAMP,
    ALTER COLUMN deleted_at SET DATA TYPE TIMESTAMP;

ALTER TABLE login_sessions
    ALTER COLUMN created_at SET DATA TYPE TIMESTAMP,
    ALTER COLUMN updated_at SET DATA TYPE TIMESTAMP,
    ALTER COLUMN deleted_at SET DATA TYPE TIMESTAMP;

ALTER TABLE song_requests
    ALTER COLUMN created_at SET DATA TYPE TIMESTAMP,
    ALTER COLUMN updated_at SET DATA TYPE TIMESTAMP,
    ALTER COLUMN deleted_at SET DATA TYPE TIMESTAMP;

ALTER TABLE track_metadata
    ALTER COLUMN created_at SET DATA TYPE TIMESTAMP,
    ALTER COLUMN updated_at SET DATA TYPE TIMESTAMP,
    ALTER COLUMN deleted_at SET DATA TYPE TIMESTAMP;

ALTER TABLE users
    ALTER COLUMN created_at SET DATA TYPE TIMESTAMP,
    ALTER COLUMN updated_at SET DATA TYPE TIMESTAMP,
    ALTER COLUMN deleted_at SET DATA TYPE TIMESTAMP,
    ALTER COLUMN spotify_token_expiry SET DATA TYPE TIMESTAMP;
COMMIT;
